spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://111.231.102.115:3306/activiti?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: '*@123AOJDaojd'
#  activiti:
#    database-schema-update: true
#    process-definition-location-prefix: classpath:/process/
#  activiti:
#    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mysql://111.231.102.115:3306/activiti?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#    username: root
#    password: '*@123AOJDaojd'
logging:
  level:
    com:
      jsyl:
        activiti: Debug
