server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:
    username: root
    password:

logging:
  level:
    com:
      jsyl:
        activiti: Debug
    org:
      activiti: Debug

