server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: com.jsyl.activiti.util.MySQLUpperCaseStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com:
      jsyl:
        activiti: Debug
    org:
      activiti: Debug
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

